config/routes.rb
FoundationAQv2::Application.routes.draw do

  devise_for :members

  resources :posts do
    resources :comments
  end

  get "home/index"

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base 
  has_many :comments
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:author, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<!-- Header -->
<header class="myhead">
  <div class ="row">
    <div class="twelve columns">
 			<h1>Paris-Tokyo-Seattle</h1>
 			<h4>portfolio exercise</h4>
 		</div>
 	</div>
 </header>
<div class="dark" >
  <div class="row" >
    <div class="small-4 columns">
      <p class="lightT">A Technical Program Manager learning and practising Ruby on Rails</p>
    </div>
    <div class="small-8 columns">
      <blockquote>“I can't go back to yesterday because I was a different person then.”  <cite>Lewis Carroll, Alice in Wonderland</cite></blockquote>
    </div>
  </div>
</div>
<div class = "main">
  <div class="row">
    <div class="small-6 large-3 columns">
      <%= image_tag "eiffel3.jpg" %>
      <p>France</p>
    </div>
    <div class="small-6 large-3 columns">
      <%= image_tag "tokyo2.jpg" %>
      <p>Japan</p>
    </div>
    <div class="small-6 large-3 columns">
      <%= image_tag "needle2.jpg" %>
      <p>USA</p>
    </div>
    <div class=”small-6 large-3 columns”>
     <%= image_tag "rocket2.jpg" %>
     <p>Next</p>
     <hr>
     <p>Home Alicia - Bonjour! ▶︎ 
     <%= link_to "My Blog", posts_path %>
     </p>
    </div>
    <hr>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

	<!-- Navigation -->
 
  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <li><%= link_to "2014", home_index_path %></li>
        </h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
    </ul>
 
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="divider"></li>
        <li class="has-dropdown">
          <a href="#">Professional</a>
          <ul class="dropdown">
            <li><label>Section Name</label></li>
            <li class="has-dropdown">
              <a href="#" class="">Has Dropdown, Level 1</a>
              <ul class="dropdown">
                <li><a href="#">Dropdown Options</a></li>
                <li><a href="#">Dropdown Options</a></li>
                <li><a href="#">Level 2</a></li>
                <li><a href="#">Subdropdown Option</a></li>
                <li><a href="#">Subdropdown Option</a></li>
                <li><a href="#">Subdropdown Option</a></li>
              </ul>
            </li>
            <li><a href="#">Dropdown Option</a></li>
            <li><a href="#">Dropdown Option</a></li>
            <li class="divider"></li>
            <li><label>Section Name</label></li>
            <li><a href="#">Dropdown Option</a></li>
            <li><a href="#">Dropdown Option</a></li>
            <li><a href="#">Dropdown Option</a></li>
            <li class="divider"></li>
            <li><a href="#">See all &rarr;</a></li>
          </ul>
        </li>
        <li class="divider"></li>
        <li class="has-dropdown">
          <a href="#">Personal</a>
          <ul class="dropdown">
            <li><a href="#">Dropdown Option</a></li>
            <li><a href="#">Dropdown Option</a></li>
            <li><a href="#">Dropdown Option</a></li>
            <li class="divider"></li>
            <li><a href="#">See all &rarr;</a></li>
        </li>
      </ul>
        <li class="divider"></li>
        <li><a href="#">Contact Me</a></li>
        <li class="divider"></li>
        <li><% if member_signed_in? %>
        <a href="#"><%= current_member.email %></a>
        <% else %>        
        <%= link_to "Register", new_member_registration_path %>
        <% end %></li>
        <li class="divider"></li>
        <li><% if member_signed_in? %>
        <%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
        <% else %>        
       <li><%= link_to "Sign In", new_member_session_path %></li>
       <% end %></li>       
    </section>
  </nav> 

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <div class="dark">
      <footer class="row">
      <div class="large-12 columns">
        <div class="row">
          <div class="large-6 columns">
            <p class="lightT">&copy; Alicia</p>
          </div>
        </div>
      </div>
      </footer>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- Main Page Content and Sidebar -->
 
<div class="row">
 
<!-- Main Blog Content -->
  <div class="large-9 columns" role="content">

<h1>Blog - Alicia</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<br><br><br><br><br>

</div>
 
<!-- End Main Content -->

<!-- Sidebar -->
 
  <aside class="large-3 columns">
      <div class="panel">
        <h5>About</h5>
        <%= image_tag "lapin.jpg" %>
    <br><br>
        “Cat: Where are you going?<br>
Alice: Which way should I go?<br>
Cat: That depends on where you are going.<br>
Alice: I don’t know.<br>
Cat: Then it doesn’t matter which way you go.”<br>
― Lewis Carroll, Alice in Wonderland
      </div>
<br> 
    </aside>
 
    <!-- End Sidebar -->
  </div>
 
  <!-- End Main Content and Sidebar -->

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- Main Page Content and Sidebar -->

<div class="row">

<!-- Main Blog Content -->
  <div class="large-9 columns" role="content">


<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
<strong>Comments</strong>
</p>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Author:</strong>
    <%= comment.author %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>
<% end %>

<p>
<strong>Add a comment:</strong>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
</p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<br><br>

</div>

<!-- End Main Content -->

<!-- Sidebar -->

  <aside class="large-3 columns">
      <div class="panel">
        <h5>About</h5>
        <%= image_tag "lapin.jpg" %>
    <br><br>
        “Cat: Where are you going?<br>
Alice: Which way should I go?<br>
Cat: That depends on where you are going.<br>
Alice: I don’t know.<br>
Cat: Then it doesn’t matter which way you go.”<br>
― Lewis Carroll, Alice in Wonderland
      </div>
<br><br><br><br><br><br>
    </aside>
    <!-- End Sidebar -->
  </div>

  <!-- End Main Content and Sidebar -->